### ISSUE TITLE
Detect whether MPI compiler wrapper supports -f90 option

### ISSUE THREAD

**Issue by letmaik** [wrf-model/WPS#106]
WRF already has this check in its configure script: https://github.com/wrf-model/WRF/blob/9527846b8782cf1a137913daeb6ed267e8b2f5ca/configure#L699-L713

WPS compilation currently fails if the wrapper does not support `-f90` as its configure script does not have a corresponding check.

Note that newer wrappers have changed from `-f90` to `-fc`, which may be a more appropriate option than just leaving it out completely as WRF does currently. But note that I'm not sure if there are wrappers which have neither `-f90` nor `-fc`, which may have been the motivation for the current logic in WRF's configure script.

**Comment by mgduda** [comment]
@letmaik PR #100 actually removed the `-f90` option altogether from most of the WPS configuration options (though we left the option in place for options that were deemed to be deprecated and therefore may be removed in a future release anyway).

Are there systems of interest that cross-compile and therefore might need something like the `-f90` and `-cc` options afterall? If so, we could look into adding logic like WRF does to try to detect when to add these flags (though we'd still need to find out which compiler name should be specified along with the flags).

**Comment by letmaik** [comment]
Removing the flags seems sensible. I wasn't aware that they are useful for cross-compiling mostly.
