### ISSUE TITLE
Vtable for GFS Para (FV3)

### ISSUE THREAD

**Issue by paulm999** [wrf-model/WPS#112]
Hi, will a new Vtable be required for the updated GFS (FV3 version) due to go live in March?

**Comment by mgduda** [comment]
It's my understanding that the same Vtable.GFS should continue to work after the transition to FV3-GFS.
@jimbresch may be able to confirm whether this is indeed the case.

**Comment by jimbresch** [comment]
No, a new Vtable will not be required. However, you must use ungrib from WPS V3.9.1 (August 2017) or newer to use FV3 output.
