### ISSUE TITLE
Support Generalized Vertical Coordinates

### ISSUE THREAD

**Issue by Plantain** [wrf-model/WPS#114]
Generalized vertical coordinates are used by a number of German models, with layer heights being specified in an invariant GRIB2 such as https://opendata.dwd.de/weather/nwp/icon-eu/grib/00/hhl/

Specification:
https://www.wmo.int/pages/prog/www/ISS/Meetings/IPET-DRC_Brasilia2010/Documents/IPETDRC-II_Doc2-3_9.doc

Ability to ungrib and process layers in this format would be very useful compared to relying on pressure level model outputs for initialization.

**Comment by mgduda** [comment]
The metgrid program performs all horizontal interpolation on the coordinate surface of the data, whatever those coordinates might be, and in the real program, vertical interpolation to model eta levels is column independent. As long as you're able to provide 3-d pressure and geopotential height fields, the vertical coordinate of the meteorological data shouldn't matter (as long as it's a monotonic coordinate).

I'll close this issue for now, but if you encounter any specific problems in trying to use a dataset on a generalized vertical coordinate, feel free to re-open the issue with details of the specific problem.

**Comment by Plantain** [comment]
Thanks for looking at this.
From ICON, for the model native levels we only get:
HHL: Geometric height of model half levels above msl
(see Table 6.4 https://isabel.dwd.de/DWD/forschung/nwv/fepub/icon_database_main.pdf)

It's not clear to me whether it's possible to construct a VTable that can represent this.

**Comment by mgduda** [comment]
The approach taken with model-level output from the UM and from the IFS is to ungrib all available fields and to then use a utility program to compute those that are missing -- typically just 3-d pressure, height, and relative humidity. A similar approach may work for ICON data.

If you'd like to discuss further, I'd suggest moving the discussion to the WRF forum at http://forum.mmm.ucar.edu/ , since we're no longer discussing and issue with the WPS code.

**Comment by mgduda** [comment]
Also, in Section 6.2 of the document you referenced, it did appear as though 3-d pressure (P) was an output field, right?

**Comment by Plantain** [comment]
Picking this up again, yes, 3D pressure is an output field, as is T/QV
But ungrib.exe has no support for level code 150.
INFORM: Rd_grib2 does not know about level code 150 (field = TT). Skipping this field. If you want this level, rd_grib2.F must be modified

**Comment by grafmi** [comment]
3D pressure is available on model levels, but not geopotential height (only geometric height). Is the vertical interpolation in the real program able to handle geometric height? If so, I could implement a handling for level code 150 in rd_grib2.F.
