### ISSUE TITLE
POWER/Linux configuration needs -qufmt=be

### ISSUE THREAD

**Issue by mgduda** [wrf-model/WPS#129]
For compatibility with other systems, the binary files (principally, the intermediate files) created by the WPS program should be written in big-endian byte order. Accordingly, the `-qufmt=be` option should be added to the FFLAGS variable in the POWER/Linux stanza.

**Comment by davegill** [comment]
@mgduda 
Michael,
Supporting your position:

On page 25 of http://geco.mines.edu/prototype/How_do_you_build_applications/xl/ppc/xlf/getstart.pdf is this note:

<img width="506" alt="Screen Shot 2019-05-06 at 5 21 25 PM" src="https://user-images.githubusercontent.com/12666234/57261059-8e97f380-7023-11e9-8cd8-ae2901c3435a.png">

**Comment by mgduda** [comment]
This issue has been resolved as of the merge of PR #147 .
