### ISSUE TITLE
geogrid.exe fails due to geog directory named "_con"

### ISSUE THREAD

**Issue by conorsy** [wrf-model/WPS#135]
Hi all,

I raised a bug with the WRF-CMake gang, and they gave me a work-around for it, but suggested I'd log it here to, to make you guys aware of a Windows issue: https://github.com/WRF-CMake/wrf/issues/43

## Describe the bug
geogrid.exe is looking for orography data in DATA\geog/orogwd_1deg/con/index. However, windows does not allow any directory to be named "con". When geog data are unpacked, this directory gets named "_con", and cannot be renamed to "con". Hence, geogrid.exe fails.

## To Reproduce
- Run geogrid.exe following standard test case on https://gis4wrf.github.io/tutorials/wrf-cmake/simulate-the-2018-european-heat-wave-with-wrf-cmake/#download-geographical-data

## Expected behavior
Code is actually behaving as expected. The problem is the path geogrid.exe uses to search for orography data, and the inability of Windows to name a directory "con".

## System information (please complete the following information):
- Windows 10 pro
- Using downloaded binary wps-cmake-4.1.0-basic_nesting-serial-x64-windows-release.zip

## Additional context
The code runs, so it's not really a bug, but geogrid.exe won't work without the orog data, so it's not really a feature request either...

**Comment by mgduda** [comment]
It seems like simply renaming the `con` sub-directories in the `GEOGRID.TBL` file to `_con` might allow the WPS to handle the renaming that Windows performs:
```
===============================
name = CON
        priority = 1
        dest_type = continuous
        masked=water
        fill_missing=0.
        interp_option = default:average_4pt
        interp_option =  lowres:wt_average_4pt
        interp_option = 10m:average_4pt
        interp_option = 20m:average_4pt
        interp_option = 30m:average_4pt
        interp_option = 1deg:average_4pt
        interp_option = 2deg:average_4pt
        rel_path = default:orogwd_10m/_con/
        rel_path =  lowres:orogwd_1deg/_con/
        rel_path = 10m:orogwd_10m/_con/
        rel_path = 20m:orogwd_20m/_con/
        rel_path = 30m:orogwd_30m/_con/
        rel_path = 1deg:orogwd_1deg/_con/
        rel_path = 2deg:orogwd_2deg/_con/
===============================
```
I think we'd be disinclined to make this change in the repository, but it might be another option for Windows users.

**Comment by conorsy** [comment]
Thanks @mgduda, that's a good suggestion. I'll pass it back to the WRF-CMake gang, suggesting they make that change in GEOGRID.TBL for their Windows builds.
