### ISSUE TITLE
metgrid.exe makes file system unwritable

### ISSUE THREAD

**Issue by imbakassinn** [wrf-model/WPS#153]
I am trying to run metgrid.exe on ERA5 pl files. ungrib runs without issues and metgrid runs ok for some time. After some time metgrid.exe crashes. The last lines of metgrid.log follow:

> INFORM: Going to create the field SOILT
> INFORM: Couldn't find SOILT000 at level 200100.000000 to fill level 0.000000 of SOILT.
> INFORM: Couldn't find SOILT005 at level 200100.000000 to fill level 5.000000 of SOILT.
> INFORM: Couldn't find SOILT020 at level 200100.000000 to fill level 20.000000 of SOILT.
> INFORM: Couldn't find SOILT040 at level 200100.000000 to fill level 40.000000 of SOILT.
> INFORM: Couldn't find SOILT160 at level 200100.000000 to fill level 160.000000 of SOILT.
> INFORM: Couldn't find SOILT300 at level 200100.000000 to fill level 300.000000 of SOILT.
> INFORM: Couldn't find SOILT050 at level 200100.000000 to fill level 49.000000 of SOILT.
> INFORM: Couldn't find SOILT050 at level 200100.000000 to fill level 51.000000 of SOILT.
> INFORM: Couldn't find SOILT001 at level 200100.000000 to fill level 1.000000 of SOILT.
> INFORM: Couldn't find SOILT004 at level 200100.000000 to fill level 4.000000 of SOILT.
> INFORM: Couldn't find SOILT010 at level 200100.000000 to fill level 10.000000 of SOILT.
> INFORM: Couldn't find SOILT030 at level 200100.000000 to fill level 30.000000 of SOILT.
> INFORM: Couldn't find SOILT060 at level 200100.000000 to fill level 60.000000 of SOILT.
> INFORM: Couldn't find SOILT100 at level 200100.000000 to fill level 100.000000 of SOILT.
> INFORM: Going to create the field SOIL_LEVELS
> INFORM: Going to create the field PRES
> INFORM: PRES at level 200100.000000 already exists; leaving it alone.
> INFORM: Field LANDSEA.mask does not have a valid mask and will not be checked for missing values
>  WRF_DEBUG: NetCDF error: Read-only file system
>  WRF_DEBUG: NetCDF error in ext_ncd_open_for_write_begin wrf_io.F90, line        1373
> ERROR: Error in ext_pkg_open_for_write_begin.
> Note: The following floating-point exceptions are signalling: IEEE_OVERFLOW_FLAG

This causes my file system to go to read only and I have to restart to be able to use the computer again. It could be a problem with the input grib files but metgrid should not put the file system to read only mode. 

I've got WPS 4.2 compiled with gfortran, serial running on Ubuntu server 18.04. I had the same problem with WPS 2.0.3

**Comment by mgduda** [comment]
If you haven't already done so, could you post this question to the WRF support forum at https://forum.mmm.ucar.edu/ ? We generally use GitHub Issues to track problems that can be traced to a specific piece of code, and that can be fixed with a code change, while the forum is used for support inquiries.
