### ISSUE TITLE
Taking too long to run ./geogrid.exe GREENFRAC

### ISSUE THREAD

**Issue by tpletzer** [wrf-model/WPS#161]
Hi I'm running ./geogrid.exe  and it gets stuck on  Processing GREENFRAC for over an hour. It seems to run quickly for a domain in the mid latitudes but my domain is over Antarctica. 

namelist.wps:

&share
 wrf_core = 'ARW',
 max_dom = 2,
 start_date = '2020-11-30_00:00:00', '2020-11-30_00:00:00', 
 end_date   = '2020-11-30_12:00:00', '2020-11-30_12:00:00', 
 interval_seconds = 21600,
 io_form_geogrid = 2,
/

&geogrid
 parent_id         = 1,1,
 parent_grid_ratio = 1,3,
 i_parent_start    = 1,96,
 j_parent_start    = 1,129,
 e_we          = 248,172,
 e_sn          = 205,172,
 geog_data_res = 'default','default',
 dx = 27000,
 dy = 27000,
 map_proj =  'polar',
 ref_lat   = -90,
 ref_lon   = -178.863,
 truelat1  = -72.828,
 truelat2  = -90,
 stand_lon = -178.863,
 geog_data_path = '/Users/tamarapletzer/wrf/downloads/WPS_GEOG',
 ref_x = 124.0,
 ref_y = 102.5,
/

&ungrib
 out_format = 'WPS',
 prefix = 'SST',
/

&metgrid
 fg_name = 'FILE', 'SST',
 io_form_metgrid = 2,
/

Any help is appreciated
Cheers

**Comment by mgduda** [comment]
Could you post this question to the WRF support forum at https://forum.mmm.ucar.edu/ ? We generally use GitHub Issues to track problems that can be traced to a specific piece of code, and that can be fixed with a code change, while the forum is used for support inquiries.
