### ISSUE TITLE
ERROR: Didn't recognize format version of data in FILE:2021-03-22_00.\nFound version 83886080 but expected either 3, 4, or 5. This could be an endian problem.

### ISSUE THREAD

**Issue by leonardojimenez1990** [wrf-model/WPS#167]
hello, Can somebody help me? How can I fix this error by running metgrid.exe. I am using WPSv4 and WRFv4.2.2, Intel, foltran90, Big edianHow can I fix this error by running metgrid.exe. I am using WPSv4 and WRFv4.2.2.
#
#   Settings for Linux x86_64, Intel compiler    (dmpar) 
#
#
COMPRESSION_LIBS    = -L/gpfs/GLOBAL_JOB_REPO_KPFU/gurianov/intel/grib2/lib -ljasper -lpng -lz
COMPRESSION_INC     = -I/gpfs/GLOBAL_JOB_REPO_KPFU/gurianov/intel/grib2/include
FDEFS               = -DUSE_JPEG2000 -DUSE_PNG
SFC                 = ifort
SCC                 = icc
DM_FC               = mpif90 -f90=ifort
DM_CC               = mpicc -cc=icc
FC                  = $(DM_FC)
CC                  = $(DM_CC)
LD                  = $(FC)
FFLAGS              = -FR -convert big_endian
#FFLAGS              = -ffree-form -O -fconvert=big-endian -frecord-marker=4
F77FLAGS            = -FI -convert big_endian
#F77FLAGS            = -ffixed-form -O -fconvert=big-endian -frecord-marker=4
FCSUFFIX            = 
FNGFLAGS            = $(FFLAGS)
LDFLAGS             = 
CFLAGS              = -w
CPP                 = /lib/cpp -P -traditional
CPPFLAGS            = -D_UNDERSCORE -DBYTESWAP -DLINUX -DIO_NETCDF -DIO_BINARY -DIO_GRIB1 -DBIT32 -D_MPI
ARFLAGS             =
CC_TOOLS            = 

Data GFS

configure.wps
FFLAGS = -FR -convert big_endian
F77FLAGS = -FI -convert big_endian

[configure.wps.log](https://github.com/wrf-model/WPS/files/6195453/configure.wps.log)
[geogrid.log](https://github.com/wrf-model/WPS/files/6195402/geogrid.log)
[metgrid.log](https://github.com/wrf-model/WPS/files/6195403/metgrid.log)
[ungrib.log](https://github.com/wrf-model/WPS/files/6195404/ungrib.log)

**Comment by weiwangncar** [comment]
@leonardojimenez1990 Please post this on the Forum: https://forum.mmm.ucar.edu. Thanks.
