### ISSUE TITLE
Getting errors while compile

### ISSUE THREAD

**Issue by krishnaap** [wrf-model/WPS#179]
While compiling WPS I am getting errors, because jasper possible default path given in the confgure.wps as this

#
#   Settings for Linux x86_64, gfortran    (dmpar) 
#
#
COMPRESSION_LIBS    = -L/glade/u/home/wrfhelp/UNGRIB_LIBRARIES/lib -ljasper -lpng -lz
COMPRESSION_INC     = -I/glade/u/home/wrfhelp/UNGRIB_LIBRARIES/include

When I edit and give complete path to my jasper folder, its working fine. Why isn't taking $JASPERLIB and $JASPERINC given already?

**Comment by mgduda** [comment]
Could you post this question to the WRF support forum at https://forum.mmm.ucar.edu/ ? We generally use GitHub Issues to track problems that can be traced to a specific piece of code, and that can be fixed with a code change, while the forum is used for support inquiries.

**Comment by qwdy** [comment]
Hi, I have met the same problem about COMPRESSION_LIBS and COMPRESSION_INC ,did you figure out the reason?

**Comment by weiwangncar** [comment]
@qwdy Could you post this question to the WRF support forum at https://forum.mmm.ucar.edu/ ?
