### ISSUE TITLE
geogrid.exe : formatted I/O to unit open for unformatted transfers, unit 10 , file namelist.wps

### ISSUE THREAD

**Issue by KapilS25** [wrf-model/WPS#198]
[Getting](url) following error while running ./geogrid.exe

forrtl: severe (257): formatted I/O to unit open for unformatted transfers, unit 10, file WPS/namelist.wps
Image              PC                Routine            Line        Source
libnetcdf.so.19.0  00002B2A6945B1D6  for__io_return        Unknown  Unknown
geogrid.exe        00000000005BEC71  for_read_seq_nml      Unknown  Unknown
geogrid.exe        000000000040D36E  Unknown               Unknown  Unknown
geogrid.exe        000000000040BC55  Unknown               Unknown  Unknown
geogrid.exe        000000000040A5B2  Unknown               Unknown  Unknown
libc-2.17.so       00002B2A6B511555  __libc_start_main     Unknown  Unknown
geogrid.exe        000000000040A4A9  Unknown               Unknown  Unknown

WPS compiled using configure option 19 (Intel Compiler dmpar)

Dependencies Used : 
Intel Compiler 2019.5
hdf5 1.12.1
netcdf c-4.8.0-cxx-4.3.1-f-4.5.3
pnetcdf 1.12.2
libpng 1.6.36
jasper 1.900.1
flex 2.6.3

namelist.wps file :
&share
 wrf_core = 'ARW',
 max_dom = 1,
 start_date = '2016-10-06_00:00:00',
 end_date = '2016-10-08_00:00:00',
 interval_seconds = 21600,
/

&geogrid
 parent_id         =   1,
 parent_grid_ratio =   1,
 i_parent_start    =   1,
 j_parent_start    =   1,
 e_we              =  91,
 e_sn              =  100,
 geog_data_res = 'default',
 dx = 27000,
 dy = 27000,
 map_proj = 'mercator',
 ref_lat   =  28.00,
 ref_lon   = -75.00,
 truelat1  =  30.0,
 truelat2  =  60.0,
 stand_lon = -75.0,
 geog_data_path = '<path to>/WPS_GEOG',
/

&ungrib
 out_format = 'WPS',
 prefix = 'FILE',
/

&metgrid
 fg_name = 'FILE',
/

**Comment by weiwangncar** [comment]
@KapilS25 This question belongs to the Forum: https://forum.mmm.ucar.edu/. Please carefully check your namelist.wps file, and compare it to one of the provided ones.
