### ISSUE TITLE
Why is RH set to 5% between 300 and 70 hPa and Set RH to 0 above 70 hPa in WPS/ungrib/src/rrpr.F？

### ISSUE THREAD

**Issue by andrewsoong** [wrf-model/WPS#200]
Hello，
I just wonder that RH was set to 5% between 300 and 70 hPa and Set RH to 0 above 70 hPa in WPS/ungrib/src/rrpr.F.
（https://github.com/wrf-model/WPS/blob/master/ungrib/src/rrpr.F) lines: 686-697.
This makes the RH between 300 and 70 hPa in met_em_d0x.nc smaller than the GFS.

**Comment by mgduda** [comment]
The block of code you mention on [lines 672 - 697](https://github.com/wrf-model/WPS/blob/v4.3.1/ungrib/src/rrpr.F#L672-L697) fills in levels in the RH field that are missing -- note the if-test on [line 689](https://github.com/wrf-model/WPS/blob/v4.3.1/ungrib/src/rrpr.F#L689). If the GFS provides larger values (or any values at all) for levels above 300 hPa, then the code in question should not be modifying the RH field.

**Comment by andrewsoong** [comment]
Thank you! But my RH of Met file is smaller than the GFS.

**Comment by mgduda** [comment]
@andrewsoong I would suggest posting this to the WRF support forum at https://forum.mmm.ucar.edu/.
