### ISSUE TITLE
Let's get familiar with the data by running g2print on one of the data files

### ISSUE THREAD

**Issue by GISerlingqing** [wrf-model/WPS#202]
When I run ./util/g2print.exe ../DATA/matthew/fnl_20161006_00_00.grib2 , the programm appear the error that *** Error in `./util/g2print.exe': corrupted size vs. prev_size: 0x000000000252ef90 ***. Has anyone ever encountered this problem before? and how did you solve it? think you

**Comment by weiwangncar** [comment]
@GISerlingqing Please post issues like this in the user forum: https://forum.mmm.ucar.edu/.
