### ISSUE TITLE
geogrid.exe of WPS 4.4 could not run

### ISSUE THREAD

**Issue by andrewsoong** [wrf-model/WPS#208]
Hi, all
I have a problem that the geogrid.exe of WPS 4.4 could not run. And the geogrid.exe was compiled successfully.
My compiler is Intel 2018(v2018.1.48).
The WPS v4.3.1 was running successfully with the same compiler and netcdf.
Does anyone have the same problem？
How to resolve ？
Thanks！

**Comment by weiwangncar** [comment]
@andrewsoong This should be posted on the Forum: https://forum.mmm.ucar.edu/. Thanks.
