### ISSUE TITLE
metgrid

### ISSUE THREAD

**Issue by samyaghoubi** [wrf-model/WPS#209]
Hi
I have a issue in compiling of WPS4.4 and there is no metgrid.exe. i have attached my compile.log file.
thanks
[compile.log](https://github.com/wrf-model/WPS/files/9859917/compile.log)

**Comment by mgduda** [comment]
Please use the WRF support forum at https://forum.mmm.ucar.edu to ask these sorts of questions. We generally use GitHub Issues to track code bugs or to-do items, and not for providing assistance.
