### ISSUE TITLE
How to use 1hourly/0.2° CFSv2 to drive WRF?

### ISSUE THREAD

**Issue by ZHH612** [wrf-model/WPS#217]
There are  vtables  about CFSR or 6hours/0.5° CFSV2 to drive WRF, except 1hourly/0.2° CFSv2. Does anyone have idea to figure that questions?

Here is this download address (hourly CFSv2)
https://rda.ucar.edu/datasets/ds094.1/index.html#cgi-bin/datasets/getWebList?dsnum=094.1&action=customize&disp=

**Comment by mgduda** [comment]
Please post questions of this nature to the WRF/MPAS forum at https://forum.mmm.ucar.edu/.
