### ISSUE TITLE
All value in WRF output is NaN after version 4.4

### ISSUE THREAD

**Issue by LeonTHLin** [wrf-model/WPS#226]
Hello 

I noticed that in some cases which may be a extreme precipitation event the value stored in wrfout is mostly NaN. 
This issue only happen after version 4.4 (below version 4.3.2 work well).

I operated WRF model compiled by NVHPC on AWS EC2 C7. The attachments are the sample of wrfout and namelist.
 
[wrf issue.zip](https://github.com/wrf-model/WPS/files/11340947/wrf.issue.zip)

**Comment by weiwangncar** [comment]
@LeonTHLin Can you see if the configure.wrf file have any differences? Also please report this on the [Forum](https://forum.mmm.ucar.edu/).
