### ISSUE TITLE
A bug in WPS-V4.5 about ICON-Global data processing

### ISSUE THREAD

**Issue by andrewsoong** [wrf-model/WPS#227]
Hello， WPS development team, @weiwangncar @grafmi @WQadam
There is a bug in WPS-V4.5 about  ICON-Global data processing when the ICON-Global data was ungrib.
Although the ICON product specification（https://www.dwd.de/DWD/forschung/nwv/fepub/icon_database_main.pdf） states that ICON-global soil moisture is measured in kg/m2 and that the range of values for soil moisture is 0-1. In WPS/ungrib/SRC/RRPR. F, this soil moisture (kg/m2) is converted to soil volumetric water content (m3/m3) , which results in wrong met output in WPS:met_em.d01.*.nc. The soil moisture in the NC file is between 0，0.05, which is too dry to be practical, and I think it's wrong. The spatial distribution and numerical range of soil moisture in the original ICON-Global data are consistent with the actual soil moisture , so I think the unit of soil moisture data in ICON-Global is m3/m3, not kg/m2 as indicated in the specification（https://www.dwd.de/DWD/forschung/nwv/fepub/icon_database_main.pdf）.
I tried to modify the code: WPS/ungrib/SRC/RRPR. F(Line 1448-1455) soil moisture conversion fragment, the results are in line with the actual.
I have post it on WRF-Forum: https://forum.mmm.ucar.edu/threads/a-bug-in-wps-v4-5-about-icon-global-data-processing.12955/

Thanks!
Dr. SOONG
2023-04-28

**Comment by WQadam** [comment]
Hi Dr Song,

Very sorry about this. After some investigation this is not a problem with DWD or WPS. If you are using the download script i provided i left in some code which does the conversion from kg/m2 to m3/m3 on the download (this was before i had written the code in rrpr and didnt realise i hadnt downloaded the global side of things that long ago and thought i had stripped out all the old code before sending the file across).

Please see the updated download script below for your pleasure with me deleting the offending code. 
[icon_download_modlv_global.txt](https://github.com/wrf-model/WPS/files/11354045/icon_download_modlv_global.txt)

Please note that really it is the users responsibility to check downloaded files and download scripts as currently they arent directly provided through WPS or WRF. I will try to edit the script on PR so it doesnt cause confusion with this one.

**Comment by andrewsoong** [comment]
> Hi Dr Song,
> 
> Very sorry about this. After some investigation this is not a problem with DWD or WPS. If you are using the download script i provided i left in some code which does the conversion from kg/m2 to m3/m3 on the download (this was before i had written the code in rrpr and didnt realise i hadnt downloaded the global side of things that long ago and thought i had stripped out all the old code before sending the file across).
> 
> Please see the updated download script below for your pleasure with me deleting the offending code. [icon_download_modlv_global.txt](https://github.com/wrf-model/WPS/files/11354179/icon_download_modlv_global.txt)
> 
> Please note that really it is the users responsibility to check downloaded files and download scripts as currently they arent directly provided through WPS or WRF. I will try to edit the script on PR so it doesnt cause confusion with this one.

@WQadam you are right. Thank you so much ! I will close this issue!
