### ISSUE TITLE
How to properly set the projection in GEOGRID

### ISSUE THREAD

**Issue by jbensabat** [wrf-model/WPS#228]
Hello 
I am new to GEOGRID and WRF and I am trying to create a grid and a nested grid with a higher resolution
the borders of the low resolution grid depend on the project (obviously). The problem is that I do not see an explanation on how to set the parameters for a specific projection
For Example for Israel I use WGS84 with the following data

dx = 1000.0
dy = 1000.0
 map_proj = 'mercator',
 ref_lat   =  31.37,   // lat of the domain center
 ref_lon   =  34.93,  // lon of the domain center
 truelat1  =  31.7343937, // true latitude of the origin 
 truelat2  =  34.17, // not needed by mercator (according to the doc)
 stand_lon =  34.93, // suggested by doc to be equal to ref_lon

with these parameters I get that the left corner coordinates of the low resolution grid is different than the WGS84 bound coordinates 
this creates a problem for properly locating the (i,j) starting point of the child grid

also in this files there 4 coordinates 
CLONG,CLAT
XLAT_C , XLONG_C
XLAT_U, XLONG_U
XLAT_V, XLONG_V
XLAT_M, XLONG_M

Is there any doc explaining the differences and the puporse of these coordinates ?
thanks
jac

**Comment by weiwangncar** [comment]
@jbensabat Please post this question on the Forum: https://forum.mmm.ucar.edu/. It might also help to see tutorial talks on WPS (e.g. https://www2.mmm.ucar.edu/wrf/users/tutorial/tutorial_presentation_winter_2020.htm) or read the Users' Guide (https://www2.mmm.ucar.edu/wrf/users/docs/user_guide_v4/v4.4/users_guide_chap3.html).
