### ISSUE TITLE
Unable to generate any *.exe when compiling WPS

### ISSUE THREAD

**Issue by qwdy** [wrf-model/WPS#234]
Hello everyone!
I compiled WRF successfully, but I have trouble compiling WPS which no geogrid.exe, ungrib.exe, metgrid.exe were generated.I attach my configure.wps file and log.compile file below.
Actually, I found something strange in the configure.wps file which are the 'COMPRESSION_LIBS' and 'COMPRESSION_INC'.The paths followed them doesn't exist in my computer. But even though I edited them to: (as you can see ,I use WRF in COAWST, so the directory structure is different with that in the WRF manual)

COMPRESSION_LIBS = -L/home/coawst/Build_COAWST/LIBRARIES/jasper/lib -L/home/coawst/Build_COAWST/LIBRARIES/libpng/lib -L/home/coawst/Build_COAWST/LIBRARIIES/zlib/lib -ljasper -lpng -lz

COMPRESSION_INC = -I/home/coawst/Build_COAWST/LIBRARIES/jasper/include -I/home/coawst/Build_COAWST/LIBRARIES/libpng/include -I/home/coawst/Build_COAWST/LIBRARIES/zlib/include

I still got the same error. So I'm confused about two things:1)what's the real reason to the issue? 2) do I need to change the 'COMPRESSION_LIBS' and 'COMPRESSION_INC'
I'd appreciate it if somebody help me get through it.
[configure.wps.txt](https://github.com/wrf-model/WPS/files/12773451/configure.wps.txt)
[log.txt](https://github.com/wrf-model/WPS/files/12773452/log.txt)
[module_stringutil.F.txt](https://github.com/wrf-model/WPS/files/12773453/module_stringutil.F.txt)
[module_stringutil.f90.txt](https://github.com/wrf-model/WPS/files/12773454/module_stringutil.f90.txt)

**Comment by weiwangncar** [comment]
@qwdy Could you post this question to the WRF support forum at https://forum.mmm.ucar.edu/ ?

**Comment by qwdy** [comment]
Hello, I already posted it, appreciate your help, thanks
