### ISSUE TITLE
all three xxx.exe files did not generated when compiling WPS

### ISSUE THREAD

**Issue by SpringFa** [wrf-model/WPS#239]
Hello everyone!
During the installation process of WRFV4.5.1, I successfully completed the compilation of WRF. However, I encountered issues during the compilation of WPS.
I did not follow the official website tutorial for installing WRF because the necessary libraries for WRF are already installed on the supercomputer I am using. Additionally, I have installed a modified version of NSSL's WRF-ELEC. Furthermore, as I am not very familiar with Linux operations, I am seeking help here.

$LD_LIBRARY_PATH is：
/public1/soft/pnetcdf/1.6.1/icc-18/lib：
/public1/soft/libpng/1.6.37/lib：
/public1/soft/zlib/1.2.7/lib：
/public1/soft/jasper/intel18/lib：
/public1/soft/netcdf/4.4.1-parallel-icc18/lib：
/public1/soft/hdf5/1.8.13-parallel-icc18/lib：
/public1/soft/szip/2.1.1-icc18/lib：
/public1/soft/intel/2018/debugger_2018/libipt/intel64/lib：
/public1/soft/intel/2018/debugger_2018/iga/lib：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/daal/../tbb/lib/intel64_lin/gcc4.4：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/daal/lib/intel64_lin：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/ipp/lib/intel64：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/mpi/mic/lib：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/mpi/intel64/lib：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin：
/public1/soft/intel/2018/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64：/public1/home/sc50110/NCL/lib：
/opt/slurm/slurm/lib：

Here are the steps I followed to compile WPS:
$ cd WPS-release-v4.5/
$ module load mpi/intel/18.0.2-thc szip/2.1.1-wzm hdf5/1.8.13-parallel-icc18-wzm netcdf/4.4.1-parallel-icc18-wzm jasper/intel18/1.9-cjj zlib/1.2.7-thc libpng/intel18/1.6.37-cjj pnetcdf/intel18/1.6.1-icc18-cjj
$ ./configure # 19 （Linux x86_64 Intel compiler （dmpar）） was selected
$ ./compile &> compile.log

I attempted two methods found online: adding options like -liomp5 -lpthread to WRF_LIB in configure.wps, and changing the paths for COMPRESSION_LIBS and COMPRESSION_INC in configure.wps. However, none of these methods had any effect. Additionally, I noticed that some people seemed to encounter similar issues, and their solution was to use WPS V4.1 with WRF V4.2. I am not sure if using mismatched versions of WPS and WRF could lead to problems during WRF execution.

I would be greatly appreciative if someone could help me overcome this challenge.
[compile.wps.txt](https://github.com/wrf-model/WPS/files/13555089/compile.wps.txt)
[configure.wps.txt](https://github.com/wrf-model/WPS/files/13555090/configure.wps.txt)

**Comment by mgduda** [comment]
Please post support requests to the forum at https://forum.mmm.ucar.edu/.

**Comment by mgduda** [comment]
@SpringFa Thank you for following up with the solution that worked for you!
