### ISSUE TITLE
A question about GEOGRID

### ISSUE THREAD

**Issue by jbensabat** [wrf-model/WPS#247]
Hello 
I am running the geogrid application in order to create a geo file. 
I determined the domain and the cell size (500 m) in each direction 
What I see is that it creates cells that are not of equal size with some kind of periodicity.
the size of the domain is relatively small (10 km by 20 km) so I wonder if there is a justification for having cells that are not equal in size (degrees) 
any help would really be appreciated 
best
jac

**Comment by mgduda** [comment]
Can you please post your question to the WRF/MPAS support forum at https://forum.mmm.ucar.edu ?
