### ISSUE TITLE
Resources for WPS Model throw 403 error

### ISSUE THREAD

**Issue by SettRaziel** [wrf-model/WPS#256]
Hej there.
I was testing my [deployment](https://github.com/SettRaziel/wrf_archlinux/blob/development/wrf_deploy/wrf/load_geodata.sh) for the WRF model. When trying to load the required geographic data, in this case geog_low_res_mandatory.tar.gz, i am no longer able to download it. I get a 403 forbidden.
When debugging the website call i could reconstruct that you webserver now provides me with a 301 Moved Permanently, which is awesome because TLS connections are awesome. But when opening the redirected https connection i do get the mentioned 403 Forbidden error. Is there an update URL where i can find the low res and high res geograpical data?
The same happens when i try to open your helpful resources provided in the [readme.md](https://github.com/wrf-model/WPS/blob/master/README) of this repository. If your webserver now only serves https content please consider to update your resources in the readme to valid URLs.

I do not know if this issue is the right way to address that to you, so please excuse me when this is the wrong place and direct me to the right place. Thank you so much.

**Comment by mgduda** [comment]
We've been having server issues since yesterday, but we are working to get everything back up and running.

**Comment by SettRaziel** [comment]
The URLs are working again. Thank you for the explanation.
