### ISSUE TITLE
Error when ungrib.exe the ECMWF IFS 0p25 dataset

### ISSUE THREAD

**Issue by chunlei666** [wrf-model/WPS#257]
Dear Team,

I hope this message finds you well.

I am currently attempting to execute the Weather Research and Forecasting (WRF) model using the dataset provided in the link: https://data.ecmwf.int/forecasts/20240819/00z/ifs/0p25/oper/. However, I have encountered an error during the ungrib process with the following message:

“getdrstemplate: DRS Template 42 not defined.
ERROR extracting field gf_getfld = 12
Additionally, the g2print.exe utility is unable to read the GRIB2 file associated with the dataset.”

I would greatly appreciate any guidance or solutions you could offer to resolve these issues. Your expertise and assistance are invaluable to me.

**Comment by chunlei666** [comment]
@bakamotokatas  I appreciate your updates to the Vtable for ECMWF data.  I was wondering if you have come across this problem or if you might have any advice on how to address it.

**Comment by mgduda** [comment]
Can you please post your question on the WRF/MPAS forum at https://forum.mmm.ucar.edu ?
