### ISSUE TITLE
Hello, I would like to use WRF to downscale EC data. Can you provide any assistance

### ISSUE THREAD

**Issue by HongLouyemeng** [wrf-model/WPS#260]
I have successfully run WRF on GFS, and ECMWF will open[ IFS ](https://data.ecmwf.int/forecasts/20240924/00z/ifs/0p25/enfo/)Data to provide global data for free,But I found that many people in the WPS forum have encountered the Grib2 format and ECMWF.[VTable being invalid](https://forum.mmm.ucar.edu/threads/ecmwf-open-data-0p25-grib2-vtable.16523/).Can you give me some advice from a professional perspective, including variable ranges, how to add new Vtables, or what other factors should be considered？For example, do I need to mix GFS with other variables to assist ECMWF IFS in order to use WRF
1.https://forum.mmm.ucar.edu/threads/error-when-ungrib-exe-the-ecmwf-ifs-0p25-dataset-257.18725/#post-45423
2.https://forum.mmm.ucar.edu/threads/using-ecmwf-data-in-the-wrf-model.18322/#post-44404

**Comment by HongLouyemeng** [comment]
If you could provide Slack invitations, that would be even better😄

**Comment by weiwangncar** [comment]
The new EC grib2 data requires an additional step to convert from EC grib2 data to grib2 data WPS supports. The conversion can be done by using the convert command in the [ecCodes](https://confluence.ecmwf.int/display/ECC/ecCodes+Home) library which is available from ECMWF. The conversion step is like what is presented in the first post you quoted:
`grib_set -r -w packingType=grid_ccsds -s packingType=grid_simple input.grib2 output.grib2`

The updated Vtable.ECMWF in WPS v4.6 should work with the converted grib2 data.

This should be posted in the support forum. With this comment, I'm closing this post.

**Comment by HongLouyemeng** [comment]
> The new EC grib2 data requires an additional step to convert from EC grib2 data to grib2 data WPS supports. The conversion can be done by using the convert command in the [ecCodes](https://confluence.ecmwf.int/display/ECC/ecCodes+Home) library which is available from ECMWF. The conversion step is like what is presented in the first post you quoted: `grib_set -r -w packingType=grid_ccsds -s packingType=grid_simple input.grib2 output.grib2`
> 
> The updated Vtable.ECMWF in WPS v4.6 should work with the converted grib2 data.
> 
> This should be posted in the support forum. With this comment, I'm closing this post.

Thanks for your answer!😊

**Comment by HongLouyemeng** [comment]
> The new EC grib2 data requires an additional step to convert from EC grib2 data to grib2 data WPS supports. The conversion can be done by using the convert command in the [ecCodes](https://confluence.ecmwf.int/display/ECC/ecCodes+Home) library which is available from ECMWF. The conversion step is like what is presented in the first post you quoted: `grib_set -r -w packingType=grid_ccsds -s packingType=grid_simple input.grib2 output.grib2`
> 
> The updated Vtable.ECMWF in WPS v4.6 should work with the converted grib2 data.
> 
> This should be posted in the support forum. With this comment, I'm closing this post.

I use ECMWF IFS oper grid2，/Ungrib.exe executed successfully， but / Metgrid.exe execution failed
At line 111 of file gridinfo_module.f90 (unit = 10, file = 'namelist.wps')
Fortran runtime error: End of file,Can you offer me some help?
