### ISSUE TITLE
Metgrid.exe ECMWF IFS oper data error

### ISSUE THREAD

**Issue by HongLouyemeng** [wrf-model/WPS#261]
I use ECMWF IFS oper grid2，/Ungrib.exe executed successfully， but / Metgrid.exe execution failed
At line 111 of file gridinfo_module.f90 (unit = 10, file = 'namelist.wps')
Fortran runtime error: End of file,Can you offer me some help?

**Comment by mgduda** [comment]
Please post help requests in the WRF/MPAS forum at https://forum.mmm.ucar.edu/.
