### ISSUE TITLE
Vtable error of ECMWF,pls update it

### ISSUE THREAD

**Issue by HongLouyemeng** [wrf-model/WPS#263]
**1. When I use data [oper](https://data.ecmwf.int/forecasts/20241012/00z/ifs/0p25/oper/),./metegrid.exe is work, but ./ungrib.exe work,but loss some Subsoil level, log:**
<img width="1283" alt="image" src="https://github.com/user-attachments/assets/4a3e3ea2-b29d-4716-bb6c-2513023ceb9e">
**/real.exe error**:_input files : NUM_METGRID_SOIL_LEVELS = 1 (from met_em files)._
2. **When I use data[ enfo](https://data.ecmwf.int/forecasts/20241012/00z/ifs/0p25/enfo/)** ,./ungrib.exe not work:
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/ddf60e68-89e0-450f-a1f2-1d0f0d8aeffd">

**Comment by HongLouyemeng** [comment]
I don't think WPS recognises the [enfo](https://data.ecmwf.int/forecasts/20241012/00z/ifs/0p25/enfo/)  dataset based on Vtable.ECMWF QAQ.

**Comment by weiwangncar** [comment]
@HongLouyemeng Surface data including soil data may come from grib 1 data. You may need to use eccodes to separate out grib 2 and grib 1 data first before running ungrib. We are not supporting the new enfo data yet. Please post further issue on the [Forum](https://forum.mmm.ucar.edu/).

**Comment by weiwangncar** [comment]
@HongLouyemeng You can also try the method we posted on FAQ to see if it applies to this dataset.

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng You can also try the method we posted on FAQ to see if it applies to this dataset.

Hi, Dr.Wang,thanks for you take care of my question,I found other user meet the same issues like me, they are loss soil data.
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/27aad605-4ea0-4195-bca2-3a2fca1820aa">

**Comment by HongLouyemeng** [comment]
I have some goods prediction on WRF based on GFS, and now I want to use ECMWF  to do the same things, I can read fortran code,  could you please give me some guidence?

**Comment by weiwangncar** [comment]
@HongLouyemeng It looks like the grib code for soil data has been messed up somehow. For the time being, you can try to use GFS soil data together with the EC atmospheric data. If you need help doing so, try reading the WPS section of the User's Guide.

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng It looks like the grib code for soil data has been messed up somehow. For the time being, you can try to use GFS soil data together with the EC atmospheric data. If you need help doing so, try reading the WPS section of the User's Guide.

Hi, Dr.Wang,Thanks for your answer, I will try it out in the next few days

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng It looks like the grib code for soil data has been messed up somehow. For the time being, you can try to use GFS soil data together with the EC atmospheric data. If you need help doing so, try reading the WPS section of the User's Guide.

Hi,Dr.Wang,This is a bit difficult for me, I've been trying for days with nothing QAQI am using ungrib to handle ecmwf oper and GFS separately, but real.exe is not producing wrfbody!

**Comment by weiwangncar** [comment]
@HongLouyemeng Please read carefully this section of the [User's Guide](https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/wps.html#using-multiple-meteorological-data-sources) for using combined datasets.

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng Please read carefully this section of the [User's Guide](https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/wps.html#using-multiple-meteorological-data-sources) for using combined datasets.

thank you QAQ

**Comment by HongLouyemeng** [comment]
> @HongLouyemeng Please read carefully this section of the [User's Guide](https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/wps.html#using-multiple-meteorological-data-sources) for using combined datasets.

我知道如何处理这个问题了，谢谢王博士
